# Generated by Django 6.0.4 on 2026-04-24 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0006_add_status_to_category_product'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stores.store'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('store', 'user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('store', 'user', 'product')},
        ),
    ]
