# Generated by Django 6.0.4 on 2026-04-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_add_notification_model'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stores.store'),
        ),
    ]
