# Generated by Django 6.0.4 on 2026-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_drop_authtoken_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('store_owner', 'Store Owner'), ('store_admin', 'Store Admin')], default='store_admin', max_length=20),
        ),
    ]
