# Generated by Django 6.0.4 on 2026-04-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store'),
        ),
    ]
