# Generated by Django 6.0.4 on 2026-05-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_sitesettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
