# Generated by Django 6.0.4 on 2026-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_clear_store_identity_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='review_edit_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after submission a customer can edit/delete their review. 0 = unlimited.'),
        ),
    ]
