# Generated by Django 6.0.4 on 2026-04-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Stats',
                'verbose_name_plural': 'Dashboard Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
