# Generated by Django 6.0.4 on 2026-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dashboardstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return-Requested', 'Return Requested'), ('Return-Approved', 'Return Approved'), ('Returned', 'Returned')], db_index=True, default='Pending', max_length=20),
        ),
    ]
