# Generated by Django 6.0.4 on 2026-04-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('birthday_coupon_enabled', models.BooleanField(default=True)),
                ('birthday_coupon_discount', models.PositiveIntegerField(default=20)),
                ('birthday_coupon_validity_days', models.PositiveIntegerField(default=30)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('online_payment_enabled', models.BooleanField(default=True)),
                ('cod_min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_minutes', models.PositiveIntegerField(default=15)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('store_owner', 'Store Owner'), ('store_admin', 'Store Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('store', 'user')},
            },
        ),
    ]
